version: "3.0"

services:
  book-application:
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - DOCKER_USERNAME=rainx14
      - DOCKER_PASSWORD=Nopassword14